//
//  Protein.swift
//  VFood Discovery
//
//  Created by Quynh Nguyen on 4/19/23.
//

import Foundation

struct Protein: Identifiable{
    let id = UUID()
    let name: String
    let vietName: String
    let description: String
    let image: String
}

extension Protein {
    static let all: [Protein] = [
        Protein(name: "Vietnamese Shaking Beef", vietName: "Bò Lúc Lắc", description: "The main star of bò lúc lắc is diced marinated beef. The meat is shortly seared before it is served on a bed of watercress and sliced tomatoes. Additional toppings may include pickled onions, and a dipping sauce resembling lime-based vinaigrette can be drizzled over the meat or served on the side. \n The dish was once a rare treat that was mainly prepared and served on special events. Nowadays, it is more common, but bò lúc lắc is still considered a restaurant specialty and a dish that is traditionally reserved for special occasions. \n It is also popular abroad and typically goes under the name Vietnamese shaking beef—which was inspired by its original name lúc lắc that describes the act of tossing or shaking the beef while it's being seared. A similar dish exists in Cambodia where it is better known as lok lak.\n It is believed that bò lúc lắc was inspired by the French culinary tradition that was present in Vietnam. ", image: "boluclac"),
        Protein(name: "Cured Fermented Beef or Pork", vietName: "Nem Chua", description: "Nem chua is a traditional Vietnamese dish of cured and fermented meat. Although the dish is traditionally made from pork, it can also be made with other types of meat such as beef. In order to prepare it, lean pork is minced, then combined with sliced pork skin, spices, chili peppers, and garlic. \n The combination is wrapped into banana leaves, then stored for the fermentation process from 3 to 5 days in a cold place. These rolls have a sweet, salty, spicy, and sour flavor, and they're usually served as a snack or an appetizer with raw garlic on top, and fish sauce or chili sauce on the side. \n They can also be grilled. Nem chua is especially popular for the Lunar New Year celebrations.", image: "nemchua"),
        Protein(name: "Vietnamese Ham", vietName: "Chả Lụa", description: "Whether it is referred to as chả lụa in the central and southern parts of the country, or as giò lụa in the northern regions, this famous pork delicacy is one of the most common meat products in Vietnam.\n Before it is wrapped in banana leaves and steamed, the meat is pounded into a thick paste and seasoned with various spices, starchy flour, and fish sauce. Characterized by its dense, homogenous texture and pale color, chả lụa is a staple ingredient in traditional Vietnamese cuisine. \n Often referred to as a sausage, ham, or a meatloaf, sliced chả lụa is always served on Vietnamese New Year, but it is also enjoyed as a condiment or a complement to various everyday dishes.", image: "chalua"),
        Protein(name: "Vietnamese Pork Aspic", vietName: "Thịt Đông", description: "Thịt đông is a Vietnamese take on aspic. The dish is prepared by slowly boiling pork meat and various pork cuts such as trotters and hocks, as well as pork skin, carrots, mushrooms, and different spices. When cooked, the combination is left to set until it achieves its typical jellied texture. \n The dish is usually associated with northern Vietnam, and it is often enjoyed on Vietnamese New Year. It is best served with pickled onions and a bowl of rice on the side.", image: "thitdong"),
        Protein(name: "Beef in Vinegar Hot Pot", vietName: "Bò Nhúng Dấm)", description: "Bò nhúng dấm is a Vietnamese version of a hot pot that is traditionally served communal style. In its basic form, the dish consists of a vinegar-flavored broth that may also include coconut milk or coconut water, lemongrass, onions, or other additions, while typical accompaniments include thinly sliced raw beef and an assortment of fresh vegetables and herbs such as bean sprouts, daikon, lettuce, cucumbers, mint, basil, and perilla leaves. \n Although the name (bò) suggests the dish is exclusively made with beef, it can also include other types of protein such as squids or shrimps. Additional elements include rice paper sheets, which are used as wrappers, and typically nước chấm and mắm nem dipping sauces.", image: "bonhungdam"),
        Protein(name: "Vietnamese Steak and Eggs", vietName: "Bò Né", description: "Bò né is a traditional Vietnamese dish that's especially popular in Nha Trang. It's made with cuts of beef such as skirt steak that's marinated in spices and comes served on a sizzling hot cast iron plate with fried eggs, onions, chili sauce, and a dollop of pate. \n The dish is usually accompanied by condiments and a baguette, along with lettuce, onions, tomatoes, and cucumber. The meat is often dipped into a combination of pepper sauce, lime juice, and salt, while the baguette is used to pick up the remains of pate and egg yolks off the plate. \n Vietnamese steak and eggs are traditionally served for breakfast.", image: "bone"),
        Protein(name: "Vietnamese Caramelized Pork Belly", vietName: "Thịt kho tàu", description: "Thịt kho tàu is a traditional Vietnamese dish of braised and caramelized pork belly with eggs. It's made with a combination of pork belly, garlic, shallots, soy sauce, sugar, fish sauce, and hard-boiled eggs. The braising liquid usually consists of oil, garlic, shallots, and coconut water. \n The meat is sliced, parboiled, then marinated in fish sauce, sugar, onions, and soy sauce. Later on, it's simmered with aromatic herbs, the braising liquid, and eggs until tender. Once done, the dish is usually served with rice or dua chua (pickled mustard greens) on the side.\n Thịt kho tàu is especially popular during Tet (Vietnamese New Year), but it's also commonly cooked at home.", image: "thitkhotau"),
        Protein(name: "Vu Dai Braised Fish", vietName: "Cá Kho Làng Vũ Đại", description: "Vu dai braised fish is a traditional Vietnamese dish originating from the Vu Dai village, also known as Dai Hoang village. It’s made with amur fish, galangal, ginger, pork belly, shallots, chili peppers, lime juice, fish sauce, pepper, and sugar. \n The ginger, shallots, chili peppers, and galangal are finely chopped and mix, while the rest of the galangal is cut into thin slices and placed into a clay cooking pot. The galangal slices are topped with the fish, thick slices of pork belly, and finely chopped mix of ginger, shallots, galangal, and chili peppers. \n  The combination is braised for 6 to 10 hours in a mixture of fish sauce, broth mix, sugar, lime juice, and pepper. When the water in the pot becomes slightly thick, the pot is taken off the heat and the fish is ready to be served and enjoyed. This traditional recipe has been passed down from generation to generation in Vu Dai village.", image: "cakholangvudai"),
        Protein(name: "Grilled Ground Pork on Lemongrass Skewers", vietName: "Nem Lụi Huế", description: "Nem lui is a traditional Vietnamese dish originating from Hue. The dish consists of ground pork that's grilled on a lemongrass skewer. Other ingredients often include black pepper, pork skin, garlic, shallots, and fish sauce. The meat combination is rolled into a sausage shape around a lemongrass stick, and it's then brushed with oil and grilled on a coal stove until slightly charred.\n Nem lui typically comes accompanied by vegetables, Vietnamese herbs, and rice paper that's rolled like a spring roll while the grilled ground pork is used as the filling, and the combination is then dipped in a sweet and sour peanut-sesame sauce. The dish is served as a main course or a snack in the afternoon.", image: "nemluihue")
    ]
}

