//
//  Flour.swift
//  VFood Discovery
//
//  Created by Quynh Nguyen on 4/19/23.
//

import Foundation

struct Flour: Identifiable{
    let id = UUID()
    let name: String
    let vietName: String
    let description: String
    let image: String
}

extension Flour {
    static let all: [Flour] = [
        Flour(name: "Vietnamese Sandwich", vietName: "Bánh Mì", description: "In Vietnamese cuisine, bánh mì is a short baguette with thin, crisp crust and soft, airy texture. It is often split lengthwise and filled with savory ingredients like a submarine sandwich and served as a meal, called bánh mì thịt. Plain banh mi is also eaten as a staple food. \n A typical Vietnamese roll or sandwich is a fusion of meats and vegetables from native Vietnamese cuisine such as chả lụa (pork sausage), coriander leaf (cilantro), cucumber, pickled carrots, and pickled daikon combined with condiments from French cuisine such as pâté, along with red chili and buttery mayonnaise. However, a wide variety of popular fillings are used, from xíu mại (a Chinese cuisine) to even ice cream. In Vietnam, bread rolls and sandwiches are typically eaten for breakfast or as a snack.",  image: "banhmi"),
        
       Flour(name: "Clear Shrimp and Pork Dumplings", vietName: "Bánh Bột Lọc", description: "Bánh bột lọc is a small, clear-looking, chewy tapioca dumplings in Vietnamese cuisine that can be eaten as appetizers or small snacks. They are usually filled with shrimp and pork belly, often being topped with fried shallots and served with sweet chili fish sauce. It is said to have originated from Huế, as the city was once the imperial capital of the Nguyễn dynasty and known for having simple, yet sophisticated dishes. \n Bánh bột lọc can either be steamed or boiled and wrapped with or without banana leaf. With the banana leaf wrapping, it is called bánh bột lọc lá, meaning 'clear flour cake with leaf.' Without the banana leaf wrapping, it is called bánh bột lọc trần, meaning 'clear flour cake bare.' The filling is traditionally a whole grilled shrimp with the shell on and a slice of pork belly, but variations have had the filling be shrimp without the shell, no pork belly, ground pork, mushrooms, and onions. In addition to tapioca flour, corn starch and rice flour have also been known to be added in the making of the translucent wrapper.", image: "banhbotloc"),
        Flour(name: "Flat Steamed Rice Dumplings ", vietName: "Bánh Nậm ", description: "Bánh nậm is a traditional Vietnamese dumpling origianting from Hue. The batter is made with a combination of rice and tapioca flour, sugar, and salt, while the filling consists of shrimps, minced pork, salt, pepper, sugar, shallots, annatto oil, and green onions.\n The rectangular and flat dumplings are wrapped in banana leaves, then steamed. When served, bánh nậm is traditionally accompanied by fish sauce for dipping on the side. The dumplings are typically sold at the markets because the banana leaves make them easy to transport and keep the interior supple and soft.", image: "banhnam"),
        Flour(name: "Vietnamese Mini Pancakes", vietName: "Bánh Căn", description: "These savory Vietnamese pancakes are made with a thin rice flour batter. They are cooked on outdoor grills which are equipped with a specialized terracotta bánh căn mold. The mixture is poured into the mold, and the pancake is then topped with a whole shrimp and scallions, or optionally pork or quail eggs.\n The pancakes are usually served with a fish sauce on the side and various fresh herbs and leafy vegetables which are meant to be used as wrappers. It is not clear when these pancakes first appeared, but their origin is often attributed to Ninh Thuận province, although they are enjoyed throughout South Central region.\n People often confuse bánh căn and bánh khọt. Although the two are very similar, the difference lies in the fact that bánh căn (as it's called in Central Vietnam) is cooked with a bit of oil and it remains soft, while bánh khọt (as it's called in South Vietnam) is fried in oil until crunchy and contains turmeric.", image: "banhcan"),
        Flour(name: "Vietnamese Steamed Savory Rice Cake", vietName: "Bánh Bèo", description: "Bánh bèo is a popular Vietnamese steamed cake consisting of key ingredients such as rice flour, fish sauce with green chili peppers, and either shrimps or pork. Additionally, noodles, roasted peanuts, or fried onions can be added to the cake in order to improve its flavors. Apart from savory cakes, there are also sweet versions which are almost exclusively available in Hội An. \n Bánh bèo is traditionally served in a porcelain bowl with a bamboo spoon for consumption. Some people refer to it as the Vietnamese version of tapas, and it is believed that the most important characteristic of a good bánh bèo is an indentation in its center which is used for holding the flavorful, savory stuffings.", image: "banhbeo"),
        Flour(name: "Vietnamese Mini Savory Pancakes", vietName: "Bánh Khọt", description: "Bánh khọt is a savory Vietnamese pancake made with a thin rice flour batter and cooked on outdoor grills equipped with a specialized terracotta bánh khọt mold. The batter is poured into the mold, and the pancake is then topped with various savory ingredients. \n Once prepared, these small puffed pancakes are often served with aromatic herbs and leafy vegetables on the side, which can be used as wrappers. Fish sauce is also a staple accompaniment to bánh khọt. Although it’s often confused with bánh căn (as it’s called in Central Vietnam), bánh khọt is not as soft as bánh căn because it’s fried in oil until crunchy and contains turmeric, which gives it a nice yellow color, unlike bánh căn, which doesn’t contain turmeric.", image: "banhkhot"),
        Flour(name: "Vietnamese Sticky Rice Dumplings", vietName: "Bánh Ít Trần", description: "Bánh ít trần is a traditional Vietnamese rice dumpling. The dough is made from rice flour, salt, and water, while the filling is often a mixture of mung beans, pork or shrimp, onions, salt, and pepper. Once assembled, they're traditionally wrapped in banana leaves and steamed, then drizzled with onion oil.\n These savory dumplings are usually served with a dipping fish sauce and a combination of pickled carrots and white onions.", image: "banhittran"),
        Flour(name: "Crispy Vietnamese Pancake", vietName: "Bánh xèo", description: "Loosely translated as sizzling pancakes, bánh xèo is a famous Vietnamese dish that combines crunchy crêpes with a variety of savory ingredients. The distinctive Vietnamese element in these nourishing pancakes is rice flour, which is combined with water, turmeric, and coconut milk or coconut cream in order to create the thick yellow batter. \n Additional ingredients, most commonly scallions, bean sprouts, shrimps, and cubed pork or beef, are sautéed before the mixture is added to the pan. The pancake is pan-fried at a low temperature and gently folded in half, keeping the ingredients safely tucked inside the pancake. \n Bánh xèo is eaten everywhere in Vietnam, with slight regional differences in ingredients. Traditionally, it is served in a unique way, usually complemented with vegetables such as lettuce, carrots, and cucumbers, heavily seasoned with fresh cilantro, mint, and parsley.\n Famous nuoc cham sauce, made with fish sauce, lime juice, sugar, chopped chili peppers, and garlic is typically served alongside bánh xèo. The pancakes are always freshly prepared and are supposed to be torn in larger pieces, which are usually wrapped in lettuce or rice paper and eaten by hand. \n The dish is also a popular street food item in Cambodia and Thailand.", image: "banhxeo"),
        Flour(name: "Steamed Wet Pancakes", vietName: "Bánh Ướt", description: "Bánh ướt are paper-thin, almost translucent Vietnamese pancakes that are made with rice flour and tapioca or potato starch. Traditionally, they are steamed on specialized steamers and are typically served rolled, usually accompanied by nước chấm (fish sauce), chả lụa sausage, pork, and fried shallots.\n Loosely translated as wet cakes, bánh ướt is a popular street food item that's usually associated with Nha Trang, and it is regarded as a less elaborate, local version of bánh cuốn rolls.", image: "banhuot"),
        Flour(name: "Steamed Rice Rolls Stuffed with Pork and Mushrooms", vietName: "Bánh Cuốn", description: "Bánh cuốn is a popular Vietnamese street food item consisting of steamed rice rolls stuffed with pork (banh cuon nhan thit), mushrooms (banh cuon than tri), or both (banh cuon Ha Noi). The dish is usually served with a fried shallot dip, sweet and sour fish sauce (nuoc mam chua ngot), a variety of fresh herbs, and lime-based sauce on the side. \n It takes a special kind of skill to prepare these steamed rolls which should always be extremely thin and translucent. Bánh cuốn is usually consumed for breakfast in Vietnam, while a similar version of the dish is also present in Thai cuisine, where it is known as khao phan.", image: "banhcuon")
        
    ]
}
